name: Unit Tests

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: devbotsxyz/setup-xcode@v1  # Use the correct action reference
      with:
        xcode-version: '13.0'  # Adjust the Xcode version as needed

    - name: Install dependencies
      run: |
        xcodebuild -resolvePackageDependencies
        xcodebuild -list

    - name: Build and test
      run: |
        xcodebuild test -scheme Gymondo -destination "platform=iOS Simulator,OS=15.0,name=iPhone 13"

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: Build/Logs/Test/*.xcresult
